// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLOiBMZJeZSUrf_bsVKcyBaM1ZZz916XQ',
    appId: '1:716736865363:web:277a3b82f5b961cc02d2a6',
    messagingSenderId: '716736865363',
    projectId: 'digipanchayat-fdc72',
    authDomain: 'digipanchayat-fdc72.firebaseapp.com',
    storageBucket: 'digipanchayat-fdc72.appspot.com',
    measurementId: 'G-J2JKDB9XYK',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLOiBMZJeZSUrf_bsVKcyBaM1ZZz916XQ',
    appId: '1:716736865363:web:92485de93a775aeb02d2a6',
    messagingSenderId: '716736865363',
    projectId: 'digipanchayat-fdc72',
    authDomain: 'digipanchayat-fdc72.firebaseapp.com',
    storageBucket: 'digipanchayat-fdc72.appspot.com',
    measurementId: 'G-QFXNYDBBN3',
  );
}
